### ISSUE TITLE
Sometimes the admin and bigdaddy icon in leftbar is not visible!

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#301]
Sometimes the admin and bigdaddy icon in leftbar is not visible!

**Comment by sullyfischer** [comment]
Not a high priority task. But will fix it

**Comment by YoginthS** [comment]
ok push a fix soon!

**Comment by sullyfischer** [comment]
"Not a high priority task"

**Comment by YoginthS** [comment]
👍

**Comment by YoginthS** [comment]
Still, no patch is released, so please reopen it!

**Comment by sullyfischer** [comment]
fixed

**Comment by YoginthS** [comment]
Not Fixed Displaying `Whoops, looks like something went wrong.` after login, I also cleared Cache and Views in server and also from browser

**Comment by YoginthS** [comment]
```
Type error: Argument 2 passed to Illuminate\Cache\Repository::rememberForever() must be an instance of Closure, integer given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php on line 304 (View: /var/www/html/resources/views/php-to-js-data.blade.php) (View: /var/www/html/resources/views/php-to-js-data.blade.php) (View: /var/www/html/resources/views/php-to-js-data.blade.php)
```

**Comment by YoginthS** [comment]
Still i cant see the icons on leftbar!
